# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94e06bafe38c915330e700d6a9134191792cf2419a1cf364c1b77ed212eb766933efe87d5829e255bc0394223d787baf4f47ec4d33d67e1db0e574a78e36d97a

test:
  secret_key_base: 7cdfb23049bcfe513cb0841e8fe7adc42c1c5529d3f06a88012b06a9ab2de10b017898d7371a8f3b2c7edd48f9ee43a983ef82e7a0c53adf837d8cc8ddc7a4b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
